name: Full Stack CI

on:
  push:
    branches: ["*"]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"

      - name: Make Maven executable   # falls x-Bit noch fehlt
        run: chmod +x mvnw

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test • Checkstyle • Sonar
        env:
          SONAR_TOKEN:        ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL:     ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY:  ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          set -e
          ./mvnw -B \
            -Dcheckstyle.failOnViolation=false \
            clean verify checkstyle:check sonar:sonar \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.host.url="$SONAR_HOST_URL" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.coverage.jacoco.xmlReportPaths=**/jacoco.xml \
            -Dsonar.junit.reportPaths=**/surefire-reports,**/failsafe-reports

  backend-build:
        needs: backend-ci
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"
            - name: Build JAR
              run: ./mvnw clean package -DskipTests

            - name: Upload Backend Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: clevercash-api-jar
                  path: api/target/*.jar

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  file: Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/devops-github-backend:${{ github.sha }}
                      ${{ secrets.DOCKER_USERNAME }}/devops-github-backend:latest