name: Full Stack CI

on:
    push:
        branches: ["*"]
    pull_request:
        paths:
            - "backEnd/**"

jobs:
    #################################
    # BACKEND
    #################################

    backend-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"
            - name: Make Maven Executable
              run: chmod +x mvnw

    backend-ci:
        needs: backend-setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"
            - name: Cache Maven packages
              uses: actions/cache@v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
            - name: Build, Test & Lint
              run: ./mvnw clean verify checkstyle:check
              continue-on-error: true

            - name: SonarQube Scan via Maven
              run: |
                  ./mvnw sonar:sonar \
                    -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BE }} \
                    -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                    -Dsonar.login=${{ secrets.SONAR_TOKEN }}

            - name: SonarQube Scan via Maven
              run: |
                  ./mvnw sonar:sonar \
                    -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BE }} \
                    -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                    -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                    -Dsonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports