name: Full Stack CI

on:
  push:
    branches: ["*"]
  pull_request:
    paths:
      - "backEnd/**"

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # 1) Code holen
      - uses: actions/checkout@v4

      # 2) JDK 21
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"

      # 3) mvnw ausführbar (falls x-Bit noch fehlt)
      - name: Make Maven Executable
        run: chmod +x mvnw

      # 4) Maven-Cache
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 5) Build • Test • Checkstyle • Sonar
      - name: Build, Test & Analyse
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          ./mvnw --batch-mode \
            -Dcheckstyle.failOnViolation=false \       
            clean verify checkstyle:check sonar:sonar \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=**/jacoco.xml \
            -Dsonar.junit.reportPaths=**/surefire-reports,**/failsafe-reports
